// <auto-generated />
namespace SalonKosmetyczny.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DataWizyty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataWizyty));
        
        string IMigrationMetadata.Id
        {
            get { return "202305211247171_DataWizyty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
